spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.166.2:3306/community-group-buy?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: cyl
    password: Cyl@980808
